"""Public Inbox contracts."""

from qq_time_agent.modules.inbox.contracts.models import (
    ConversationContextItem,
    ConversationContextPort,
    InboxContentPort,
    InboxContentView,
    InboxKnowledgeQueryPort,
    InboxProcessingPort,
    InboxProcessingQueryPort,
    InboxSourceDeletedError,
    InboxSourcePort,
    InboxSourceView,
    IngestResult,
    MailAddress,
    MailAttachmentMetadata,
    MailChange,
    MailDeltaPage,
    MailProvider,
    MailProviderError,
    MailSyncProvider,
    MailSyncResult,
    QqInboxPort,
)

__all__ = [
    "ConversationContextItem",
    "ConversationContextPort",
    "InboxContentPort",
    "InboxContentView",
    "InboxKnowledgeQueryPort",
    "InboxProcessingPort",
    "InboxProcessingQueryPort",
    "InboxSourceDeletedError",
    "InboxSourcePort",
    "InboxSourceView",
    "IngestResult",
    "MailAddress",
    "MailAttachmentMetadata",
    "MailChange",
    "MailDeltaPage",
    "MailProvider",
    "MailProviderError",
    "MailSyncProvider",
    "MailSyncResult",
    "QqInboxPort",
]
